### ISSUE TITLE
Hide "Unavailable" in menu bar.

### ISSUE THREAD

**Issue by legendaryaman** [tyirvine/Informant#15]
**Describe the bug**
**Unavailable** is displayed when Informant is unable to display the size of the folder for some reason.
Better Hide "Unavailable" or give an option to hide.

**How or when does this happen?**

**Informant version**
0.08.6

<img width="353" alt="Screenshot 2021-09-01 at 5 08 24 PM" src="https://user-images.githubusercontent.com/3285444/131665500-71e39f18-89df-42e3-8ed8-fee720c33019.png">

**Comment by tyirvine** [comment]
This often happens when Informant doesn't have permission to view the contents of the folder and therefore can't enumerate its contents to find a size.

I'll just hide the unavailable message in the menu bar all together as it takes a lot of space up. The details panel can then be opened to see that the size is `unavailable`.

**Comment by tyirvine** [comment]
Fixed in 0.08.7!  🎉
