### ISSUE TITLE
Dimensions stopped appearing in the menu bar

### ISSUE THREAD

**Issue by RayHollister** [tyirvine/Informant#17]
**Describe the bug**
Yesterday when I installed the app, the dimensions of jpgs, gifs and pngs appeared in the menu bar. Today, they are not appearing. I tried disabling Dimensions in the menu and re-enabling it. I tried turning all of the other options off. I tried closing the app and restarting it. None of them restored the Dimensions to the menu bar.

**How or when does this happen?**
Whenever I click on a jpg, gif and png.

**Informant version**
0.08.6

![image](https://user-images.githubusercontent.com/369131/131704360-02130b38-d240-4140-96c6-1f0c9c7cbf76.png)

The dimensions are appearing in the panel menu though...
![image](https://user-images.githubusercontent.com/369131/131704683-3876d7f5-3964-4091-a373-d15d00f77d8a.png)

**Comment by tyirvine** [comment]
Hmmm that is very strange. I'll look into this. It's odd that only the dimensions on the menu bar are not appearing.

Also I noticed that the iCloud icon is missing! I was using SF Symbols but I guess it doesn't work for all systems. I'll be sure to bake the symbols right in.

**Comment by RayHollister** [comment]
I just noticed this too...
[![Alt text](https://img.youtube.com/vi/huMEqSWDVMU/0.jpg)](https://www.youtube.com/watch?v=huMEqSWDVMU)

**Comment by tyirvine** [comment]
> I just noticed this too...
> https://www.youtube.com/watch?v=huMEqSWDVMU

@RayHollister I noticed a little iCloud icon appeared upon saving. Are those files saved in iCloud?

Are you able to see the dimensions if the file is on your Desktop or saved locally somewhere?

**Comment by tyirvine** [comment]
@RayHollister 

Okay, I think I know what's happening. The menu bar grabs it's dimension data using `kMDItemPixelWidth` & `kMDItemPixelHeight`. I like this because it'll get dimensions regardless of what kind of file it is (video, image, etc.)
<img width="892" alt="Screen Shot 2021-09-01 at 12 21 02 PM" src="https://user-images.githubusercontent.com/39813066/131723444-3697869a-0eab-4558-aaaf-2b6384a4daa5.png">

However, I added this to the panel first, and when I added it there I added it using `kCGImagePropertyPixelWidth` (and `...Height`) as you can see below ⤵︎
<img width="971" alt="Screen Shot 2021-09-01 at 12 20 42 PM" src="https://user-images.githubusercontent.com/39813066/131723410-955ad790-c892-4a41-a6df-4be9a39e4233.png">

I noticed the file uploaded to iCloud in that video, so I'm going to take a guess that, that metadata `kMDItemPixel...` is available when the file is downloaded locally but is unavailable when the item is uploaded or offloaded for some reason.

I don't actually know how to test this as all my iCloud files get the dimensions just fine so try this build I uploaded here and lmk if it works!


[Informant.zip](https://github.com/tyirvine/Informant/files/7093678/Informant.zip)

**Comment by RayHollister** [comment]
That works perfect!... on images. 🤷🏻‍♂️

On .mov and .mp4 it's still not showing anything that's in the iCloud. Newly downloaded or saved videos are showing though.

https://youtu.be/dK9F0VP_6tk

**Comment by RayHollister** [comment]
Working like a champ now on videos and images! As far as I can tell it's working on everything else too.

**Comment by tyirvine** [comment]
@RayHollister ♡＾▽＾♡

Thank you for helping me with that! I'll clean up the janky code I added and then add this fix into version 0.08.7!

**Comment by tyirvine** [comment]
I'm just gonna leave this open till it's added in 0.08.7 😊

**Comment by tyirvine** [comment]
Fixed in 0.08.7!  🎉
